### ISSUE TITLE
Update magmathon

### ISSUE THREAD

**Issue by rsetaluri** [phanrahan/magmathon#26]
- [x] Cheat sheet/language spec (ala Chisel's cheat sheet https://inst.eecs.berkeley.edu/~cs250/sp17/handouts/chisel-cheatsheet3.pdf), Raj
  * [magma cheat sheet](https://github.com/phanrahan/magma/blob/master/docs/cheat_sheet.md)
- [x] Review documentation (read the docs), Raj
- [x] Document the various ways to write modules using the different syntaxes (base, combinational, sequential), Raj
- [x] Remove warnings when importing magma/mantle (Raj, Lenny)
- [x] Check types used as input and output to testing infrastructure and simulators (Lenny)
- [x] Rerun notebooks, Pat
- [x] Switch over from icestick to coreir, Pat
- [x] Review director organization and examples, All
- [x] Simulation and testing, PythonSimulator?, Lenny
- [x] Update setup instructions, Lenny
- [x] regfile notebook, Lenny
- [x] add note about combinational polymorphism to full adder notebook, Lenny
- [x] loop unrolling in Add notebook, Lenny
- [x] More text in comb/seq notebook, Lenny

**Comment by leonardt** [comment]
Notebooks

## Basic Tutorial
Cover circuits, instances, wiring, testing/simulation, generating verilog/coreir
* FullAdder
* Add
* Register
* TFF
* Counter
* Comb/seq
* Python Debugger

## Intermediate
* Higher-order circuits
* Signal Generators
* Pop count
* Ripple counter
* Intermediate comb/seq example(s)

# Tasks
- [ ] Python/coreir simulator should be working for examples (including fault targets)
- [ ] Interactive fault frontend for python/coreir simulator
- [ ] Fill out chisel tutorial

**Comment by leonardt** [comment]
Updated setup instructions and the general README, let me know any thoughts or feel free to make changes https://github.com/phanrahan/magmathon

Things are much simpler now since we're just using a simulation based flow.

Should we meet the discuss the sessions?  The old format seemed pretty good, I adjusted the timing a bit but I think it should work pretty well, but i'm open to new ideas.

**Comment by leonardt** [comment]
Also @phanrahan when you get a moment, can you go to https://travis-ci.com/account/repositories and enable this repo on travis? Have a basic test script that walks through the setup instructions so we can make sure they're working.

**Comment by leonardt** [comment]
Python/CoreIR simulator seems to be working for all the coreir tutorial notebooks except for one issue with async reset in the coreir simulator (debugging).

Next step is to fill out the documentation on it.

One issue where we should use python vs fault simulation.  I think the main difference is staging and verilog simulator support versus interactive debugging.  It would be good to be clear about when to use which.

**Comment by leonardt** [comment]
popcount and ripple should be updated to use the coreir simulator instead of IceStick

**Comment by leonardt** [comment]
as well as signal generator

**Comment by leonardt** [comment]
CoreIR simulator now works with counter using this PR https://github.com/rdaly525/coreir/pull/848 (needed to hack in support for async reset register)
